### ISSUE TITLE
node dependency problem

### ISSUE THREAD

**Issue by phoenixperry** [vanevery/p5.serialcontrol#23]
The version of Electron that's getting used is incompatible with the app. I have tried for about 2 hours to find a way around it, but something is using version 72 and it wants version 70. 
![image](https://user-images.githubusercontent.com/783625/82829444-28d70d80-9eab-11ea-991d-a973411fc556.png)

**Comment by phoenixperry** [comment]
I can confirm it also happens on a mac. 
<img width="532" alt="Screen Shot 2020-05-25 at 5 29 00 PM" src="https://user-images.githubusercontent.com/783625/82830319-47d69f00-9ead-11ea-9801-3f7810fc5194.png">

**Comment by KrishnaMBhattarai** [comment]
same problem. This is so bad. I wish somebody fixed this. Nodejs is just horrible.

**Comment by vanevery** [comment]
Are you able to use the release rather than compiling it?

**Comment by montoyamoraga** [comment]
i think we fixed it on the newest release of this app, where we updated the dependencies, so i'm closing this issue, feel free to reopen if needed!
