### ISSUE TITLE
npm install fails on Kali linux

### ISSUE THREAD

**Issue by KrishnaMBhattarai** [vanevery/p5.serialcontrol#26]
Has anyone ever been able to work on Kali linux? Is there a guy version for linux? I tried to install the source code but it did not work. Any ideas would be helpful! I have attached my failed npm insall log ifle

Here is the `npm install` log

[npm-intall.log](https://github.com/p5-serial/p5.serialcontrol/files/8578049/npm-intall.log)

**Comment by montoyamoraga** [comment]
this is fixed with our current work on updating our dependencies, so i will close this for now, sorry about that!
