### ISSUE TITLE
build notes from Wiki in 2016

### ISSUE THREAD

**Issue by montoyamoraga** [vanevery/p5.serialcontrol#27]
this was on the Wiki, i closed it and added it here,
i am not sure if it should be added to the README.md or deleted altogether?

Build Notes:

Rebuild node-serialport from p5.serialport:

sudo HOME=~/.electron-gyp node-gyp rebuild --target=1.4.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell

Package it up for distribution:

electron-packager ./ p5.serialcontrol --version=1.4.1

**Comment by vanevery** [comment]
Having instructions for building are important - probably for the readme.

**Comment by montoyamoraga** [comment]
the README.md ones are the current ones, let's close this
