### ISSUE TITLE
Can't work with electron 1.4.1 drag app windows

### ISSUE THREAD

**Issue by stellar2016** [vanevery/p5.serialcontrol#9]
![image](https://cloud.githubusercontent.com/assets/22653489/19142417/da4732c2-8bcf-11e6-9db8-c524bd7b1430.png)
![1vt8pe vvfyk41dbimcl](https://cloud.githubusercontent.com/assets/22653489/19142442/0a238acc-8bd0-11e6-9df1-2210b98de17e.png)
![d fle 1kegpsv 0pzhky9](https://cloud.githubusercontent.com/assets/22653489/19142445/0e388c8e-8bd0-11e6-8596-8c933fb47eb1.png)

**Comment by stellar2016** [comment]
ps: i have com5 port in my local pc
![image](https://cloud.githubusercontent.com/assets/22653489/19142484/43adea08-8bd0-11e6-9c4b-683ee5f0599f.png)

**Comment by stellar2016** [comment]
after cmd : npm install, occur errors:
![image](https://cloud.githubusercontent.com/assets/22653489/19147644/a1b292be-8beb-11e6-9275-1f9b42da04f4.png)

**Comment by vanevery** [comment]
Are you trying the release?  It is a double clickable application:  https://github.com/vanevery/p5.serialcontrol/releases/tag/0.0.4

**Comment by stellar2016** [comment]
@vanevery thanks,i'll try

**Comment by stellar2016** [comment]
@vanevery it works

![image](https://cloud.githubusercontent.com/assets/22653489/19208916/50d06896-8d33-11e6-94e1-5af978ce4f9a.png)
